### ISSUE TITLE
Doesn't run correctly on x86 / `amd64` architecture

### ISSUE THREAD

**Issue by kx1t** [sdr-enthusiasts/browser-screenshot-service#3]
This keeps on repeating in the logs when running the container on an `amd64` architecture:
```
AttributeError: module 'typesystem' has no attribute 'SchemaDefinitions'
Traceback (most recent call last):
  File "/opt/app/snapapi.py", line 3, in <module>
    import responder
  File "/usr/local/lib/python3.9/dist-packages/responder/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.9/dist-packages/responder/core.py", line 1, in <module>
    from .api import API
  File "/usr/local/lib/python3.9/dist-packages/responder/api.py", line 25, in <module>
    from .ext.schema import Schema as OpenAPISchema
  File "/usr/local/lib/python3.9/dist-packages/responder/ext/schema/__init__.py", line 4, in <module>
    import apistar
  File "/usr/local/lib/python3.9/dist-packages/apistar/__init__.py", line 11, in <module>
    from apistar.core import docs, validate
  File "/usr/local/lib/python3.9/dist-packages/apistar/core.py", line 7, in <module>
    from apistar.schemas.autodetermine import AUTO_DETERMINE
  File "/usr/local/lib/python3.9/dist-packages/apistar/schemas/__init__.py", line 1, in <module>
    from apistar.schemas.openapi import OpenAPI
  File "/usr/local/lib/python3.9/dist-packages/apistar/schemas/openapi.py", line 6, in <module>
    from apistar.schemas.jsonschema import JSON_SCHEMA
  File "/usr/local/lib/python3.9/dist-packages/apistar/schemas/jsonschema.py", line 3, in <module>
    definitions = typesystem.SchemaDefinitions()
AttributeError: module 'typesystem' has no attribute 'SchemaDefinitions'
Traceback (most recent call last):
  File "/opt/app/snapapi.py", line 3, in <module>
    import responder
  File "/usr/local/lib/python3.9/dist-packages/responder/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.9/dist-packages/responder/core.py", line 1, in <module>
    from .api import API
  File "/usr/local/lib/python3.9/dist-packages/responder/api.py", line 25, in <module>
    from .ext.schema import Schema as OpenAPISchema
  File "/usr/local/lib/python3.9/dist-packages/responder/ext/schema/__init__.py", line 4, in <module>
    import apistar
  File "/usr/local/lib/python3.9/dist-packages/apistar/__init__.py", line 11, in <module>
    from apistar.core import docs, validate
  File "/usr/local/lib/python3.9/dist-packages/apistar/core.py", line 7, in <module>
    from apistar.schemas.autodetermine import AUTO_DETERMINE
  File "/usr/local/lib/python3.9/dist-packages/apistar/schemas/__init__.py", line 1, in <module>
    from apistar.schemas.openapi import OpenAPI
  File "/usr/local/lib/python3.9/dist-packages/apistar/schemas/openapi.py", line 6, in <module>
    from apistar.schemas.jsonschema import JSON_SCHEMA
  File "/usr/local/lib/python3.9/dist-packages/apistar/schemas/jsonschema.py", line 3, in <module>
    definitions = typesystem.SchemaDefinitions()
```

**Comment by ge0metrix** [comment]
Looks like a prerelease issue?

https://github.com/taoufik07/responder/issues/440
